# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - marstourist

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://webappsandapis.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7da76bdef9f1494aa913d2fd643f162b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_169197b5959a4258be657dd741d21a4a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: webappsandapis.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7da76bdef9f1494aa913d2fd643f162b }}/webappsandapis.azurecr.io/marstourist:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'marstourist'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9ca226b33e384f5d8f238f37052e5d77 }}
        images: 'webappsandapis.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7da76bdef9f1494aa913d2fd643f162b }}/webappsandapis.azurecr.io/marstourist:${{ github.sha }}'